apiVersion: skaffold/v2beta20
kind: Config
metadata:
  name: platform
build:
  artifacts:
  - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/rbac-builder
    context: builder
    docker:
      dockerfile: Dockerfile
  local:
    concurrency: 0
  # this is very important. we need to use inputDigest so that different developers don't build the same tags
  # and interfere with one another's work (e.g. when building and then running pytest you want to test the version
  # you built and not a version someone else built with the same tag)
  tagPolicy:
    inputDigest: {}

profiles:
- name: apple-m1-dev
  build:
    artifacts:
      - image: us-central1-docker.pkg.dev/genuine-flight-317411/devel/rbac-builder
        context: builder
        custom:
          buildCommand: ../build_on_apple_m1.sh
    local:
      concurrency: 0
